/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitindonesia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author irhas
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public daftar() {
        initComponents();
        
        showPasswordCheckBox.addActionListener(e -> {
            if (showPasswordCheckBox.isSelected()) {
                passwordSignup.setEchoChar((char) 0); // Tampilkan password
            } else {
                passwordSignup.setEchoChar('*'); // Sembunyikan password
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nameSignup = new javax.swing.JTextField();
        signupBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginPageBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordSignup = new javax.swing.JPasswordField();
        usernameSignup = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName("signupForm"); // NOI18N
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255,255,255, 175));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 350));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameSignup.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        nameSignup.setText("Nama Lengkap");
        nameSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameSignup.setMargin(new java.awt.Insets(2, 10, 2, 5));
        nameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameSignupFocusGained(evt);
            }
        });
        nameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSignupActionPerformed(evt);
            }
        });
        jPanel2.add(nameSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 40));

        signupBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        signupBtn.setText("Buat Akun");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel2.add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 240, -1, 40));

        jLabel1.setText("Sudah Punya Akun?");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        loginPageBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        loginPageBtn.setText("Log In");
        loginPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPageBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 35));

        exitBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        exitBtn.setText("Keluar");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 35));

        jLabel4.setText("Nama Lengkap:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        passwordSignup.setText("passwordForm");
        passwordSignup.setMargin(new java.awt.Insets(2, 10, 2, 2));
        passwordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignupFocusGained(evt);
            }
        });
        jPanel2.add(passwordSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 40));

        usernameSignup.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usernameSignup.setText("Username");
        usernameSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameSignup.setMargin(new java.awt.Insets(2, 10, 2, 5));
        usernameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignupFocusGained(evt);
            }
        });
        usernameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSignupActionPerformed(evt);
            }
        });
        jPanel2.add(usernameSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 40));

        jLabel5.setText("Username:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        showPasswordCheckBox.setText("Tampilkan Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, 300, 350));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Visit Indonesia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padar-resize.jpg"))); // NOI18N
        jPanel1.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameSignupFocusGained
        nameSignup.setText("");
    }//GEN-LAST:event_nameSignupFocusGained

    private void nameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSignupActionPerformed

    private void loginPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPageBtnActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_loginPageBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
    String namaLengkap = nameSignup.getText();
    String username = usernameSignup.getText();
    String password = new String(passwordSignup.getPassword()); // Ambil password sebagai string

    // Validasi input
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Hash password
    String hashedPassword = HashUtils.hashPassword(password);

    // Simpan ke database
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/visit_indonesia", "root", "");
         PreparedStatement stmt = conn.prepareStatement("INSERT INTO users (nama_lengkap, username, password, lvl_user) VALUES (?, ?, ?, ?)")) {
        stmt.setString(1, namaLengkap);
        stmt.setString(2, username);
        stmt.setString(3, hashedPassword);
        stmt.setInt(4, 1); // Default level user (misalnya, 1 untuk user biasa)
        
        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Tutup form saat ini
            this.dispose();

            // Buka form login
            new Login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal membuat akun. Silakan coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_signupBtnActionPerformed

    private void passwordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusGained
        passwordSignup.setText("");
    }//GEN-LAST:event_passwordSignupFocusGained

    private void usernameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusGained
        usernameSignup.setText("");
    }//GEN-LAST:event_usernameSignupFocusGained

    private void usernameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSignupActionPerformed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        //        togglePasswordVisibility();
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginPageBtn;
    private javax.swing.JTextField nameSignup;
    private javax.swing.JPasswordField passwordSignup;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernameSignup;
    // End of variables declaration//GEN-END:variables
}
