/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitindonesia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author irhas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Login() {
        initComponents();
        showPasswordCheckBox.addActionListener(e -> {
            if (showPasswordCheckBox.isSelected()) {
                passwordLogin.setEchoChar((char) 0); // Tampilkan password
            } else {
                passwordLogin.setEchoChar('*'); // Sembunyikan password
            }
        });
    }
    
    // Tambahkan listener ke checkbox



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usernameLogin = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitBtn1 = new javax.swing.JButton();
        signupPageBtn = new javax.swing.JButton();
        passwordLogin = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName("loginForm"); // NOI18N
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255,255,255, 175));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 350));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLogin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usernameLogin.setText("Username");
        usernameLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameLogin.setMargin(new java.awt.Insets(2, 10, 2, 5));
        usernameLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLoginFocusGained(evt);
            }
        });
        usernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLoginActionPerformed(evt);
            }
        });
        jPanel2.add(usernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 230, 40));

        loginBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 40));

        jLabel1.setText("Password:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        exitBtn1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        exitBtn1.setText("Keluar");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, 35));

        signupPageBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        signupPageBtn.setText("Buat Akun Baru");
        signupPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupPageBtnActionPerformed(evt);
            }
        });
        jPanel2.add(signupPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 280, -1, 35));

        passwordLogin.setText("passwordForm");
        passwordLogin.setMargin(new java.awt.Insets(2, 10, 2, 2));
        passwordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFocusGained(evt);
            }
        });
        jPanel2.add(passwordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, 230, 40));

        jLabel3.setText("Belum Punya Akun?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 260, -1, 20));

        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        showPasswordCheckBox.setText("Tampilkan Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, 300, 350));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Visit Indonesia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padar-resize.jpg"))); // NOI18N
        jPanel1.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusGained
        usernameLogin.setText("");
    }//GEN-LAST:event_usernameLoginFocusGained

    private void usernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLoginActionPerformed

    private void signupPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupPageBtnActionPerformed
        this.setVisible(false);
        new daftar().setVisible(true);
    }//GEN-LAST:event_signupPageBtnActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtn1ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameLogin.getText();
        String password = new String(passwordLogin.getPassword()); // Ambil password sebagai String
        String hashedPassword = HashUtils.hashPassword(password);
        
// Koneksi ke database
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Buat koneksi
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/visit_indonesia", "root", "");

            // Query untuk memeriksa username dan password
            String sql = "SELECT nama_lengkap, lvl_user, id, username FROM users WHERE username = ? AND password = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, hashedPassword);

            rs = pstmt.executeQuery();

            if (rs.next()) {
                
                // Simpan username ke Session
                String userID = rs.getString("id");
                String uname = rs.getString("username");
                String nama = rs.getString("nama_lengkap");

                Session.setUsername(uname);
                Session.setUserID(userID);
                Session.setNama(nama);
                
                System.out.println("User ID: " + userID);  // Menampilkan ID User
                System.out.println("Nama Lengkap: " + nama);  // Menampilkan nama lengkap

            
                // Ambil level user
                int lvlUser = rs.getInt("lvl_user");
                    System.out.println("Level User: " + lvlUser); 


                // Beralih ke form berdasarkan level user
                if (lvlUser == 1) {
//                    JOptionPane.showMessageDialog(this, "Login berhasil sebagai User!");
                    new UserForm().setVisible(true); // Buka form untuk User
                    this.dispose();
                } else if (lvlUser == 2) {
//                    JOptionPane.showMessageDialog(this, "Login berhasil sebagai Admin!");
                    new AdminForm().setVisible(true); // Buka form untuk Admin
                }
                this.dispose(); // Tutup form login
            } else {
                JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Kesalahan koneksi database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Tutup koneksi
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusGained
        passwordLogin.setText("");
    }//GEN-LAST:event_passwordLoginFocusGained

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
//        togglePasswordVisibility();
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JButton signupPageBtn;
    private javax.swing.JTextField usernameLogin;
    // End of variables declaration//GEN-END:variables
}
